// <auto-generated />
namespace FoundryMissionsCom.Migrations.FoundryMissionsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201604160604482_UserSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
