// <auto-generated />
namespace FoundryMissionsCom.Migrations.FoundryMissionsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MissionStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissionStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201604210503388_MissionStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
