// <auto-generated />
namespace FoundryMissionsCom.Migrations.FoundryMissionsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UploadExport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadExport));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250302311_UploadExport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
